### ISSUE TITLE
The link is no longer working

### ISSUE THREAD

**Issue by Niu-code998** [imperial-qore/PreGANPlus#1]
Greetings, I find the download url (http://gwa.ewi.tudelft.nl/fileadmin/pds/trace-archives/grid-workloads-archive/datasets/gwa-t-12/rnd.zip) in the web page of a data set 404 not found. Is there a new link to download the data set? Thank you for your help!

**Comment by HonestoLiu** [comment]
> Greetings, I find the download url (http://gwa.ewi.tudelft.nl/fileadmin/pds/trace-archives/grid-workloads-archive/datasets/gwa-t-12/rnd.zip) in the web page of a data set 404 not found. Is there a new link to download the data set? Thank you for your help!

Hello, how did you solve this problem?

**Comment by wkyd** [comment]
请问您是如何解决这个问题的
